## teal.toml
## Default values indicated

[project]

## File containing Teal code to be deployed
# teal_file = "service.tl"

## Location of Python source
# python_src = "src"

## Location of Python dependencies
# python_requirements = "requirements.txt"

## Location of Teal build data
# data_dir = ".teal"


[instance]

## Extra source layers to use (maximum of 4)
## e.g., from: https://github.com/keithrozario/Klayers
# extra_layers = [ ]

## Lambda function timeout (s)
# lambda_timeout = 240

## Lambda function memory (MB)
# lambda_memory = 128

## File with lambda environment variables
# env = "teal_env.txt"

## Names of S3 buckets that `teal deploy/destroy` manages
# managed_buckets = [ ]

## Names of S3 buckets to enable read/write
# s3_access = [ ]

## List of S3 upload triggers. Format: [[bucket, prefix, suffix], ... ]
## Example: [["my-bucket", "images/", ".jpg"], ...]
# upload_triggers = [ ]

## Enable the API Gateway trigger
# enable_api = false
